data:
  train: data/coco_trainval35k.json
  valid: data/coco_minival5k.json
params:
  batch_size: 6
  optimizer: Adam
  loss: focal
  lr: 1e-5
  epoch: 300
  lr_patience: -1
  lr_multistep: None
  random_seed: 3000
  image_size: 640x640
  classes: data/coco_classes.txt
  base: Res50
  pre_base: True
  num_crops: -1
  data_worker: 6
  norm_reg_target: True
  centerness_on_reg: True
  cls_threshold: 0.05
  radius: 0.6
  freeze: False
  warmup_period: -1
inference:
  image_size: 640x640
  batch_size: 10
  cls_threshold: 0.05
model:
  model_path: None
  exp_path: /data/Expr/Projects/8_object_detection/fcos/coco_mini
  is_finetune: False
cuda:
  using_cuda: True
  gpu_id: 0
